"""
Static knowledge base for the 38 plant disease classes.
Used to (a) show info cards after prediction and
(b) ground the chatbot's answers, even when no LLM API key is configured.
"""

DISEASE_INFO = {
    "Apple___Apple_scab": {
        "name": "Apple Scab",
        "symptoms": "Olive-green to black velvety spots on leaves and fruit; leaves may curl and drop early.",
        "cause": "Fungus (Venturia inaequalis), spreads in cool, wet spring weather.",
        "treatment": "Remove and destroy fallen leaves; apply a fungicide (e.g. captan or myclobutanil) starting at bud break.",
        "prevention": "Plant scab-resistant varieties; prune for airflow; clean up leaf litter every autumn.",
    },
    "Apple___Black_rot": {
        "name": "Apple Black Rot",
        "symptoms": "Purple-bordered leaf spots, and brown-to-black rotting rings on fruit ('frogeye' pattern).",
        "cause": "Fungus (Botryosphaeria obtusa), often enters through wounds or dead wood.",
        "treatment": "Prune out cankers and mummified fruit; apply fungicide during the growing season.",
        "prevention": "Sanitize pruning tools; remove dead/diseased wood every dormant season.",
    },
    "Apple___Cedar_apple_rust": {
        "name": "Cedar Apple Rust",
        "symptoms": "Bright orange-yellow spots on leaves, sometimes with tube-like structures underneath.",
        "cause": "Fungus that alternates between apple/crabapple and juniper/cedar trees.",
        "treatment": "Apply fungicide in spring; remove nearby juniper hosts if practical.",
        "prevention": "Choose rust-resistant apple varieties; keep distance from cedar trees.",
    },
    "Apple___healthy": {
        "name": "Healthy Apple Leaf",
        "symptoms": "No disease symptoms detected — leaf looks healthy.",
        "cause": "N/A",
        "treatment": "No treatment needed.",
        "prevention": "Maintain regular watering, balanced fertilization, and periodic monitoring.",
    },
    "Blueberry___healthy": {
        "name": "Healthy Blueberry Leaf",
        "symptoms": "No disease symptoms detected.",
        "cause": "N/A",
        "treatment": "No treatment needed.",
        "prevention": "Maintain soil acidity (pH 4.5–5.5) and good drainage.",
    },
    "Cherry_(including_sour)___Powdery_mildew": {
        "name": "Cherry Powdery Mildew",
        "symptoms": "White powdery coating on leaves and shoots; leaves may curl or distort.",
        "cause": "Fungus (Podosphaera clandestina), favored by warm days and cool nights.",
        "treatment": "Apply sulfur-based or systemic fungicide; prune affected shoots.",
        "prevention": "Improve air circulation through pruning; avoid excess nitrogen fertilizer.",
    },
    "Cherry_(including_sour)___healthy": {
        "name": "Healthy Cherry Leaf",
        "symptoms": "No disease symptoms detected.",
        "cause": "N/A",
        "treatment": "No treatment needed.",
        "prevention": "Regular monitoring and balanced care.",
    },
    "Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot": {
        "name": "Corn Gray Leaf Spot",
        "symptoms": "Rectangular tan-to-gray lesions running parallel to leaf veins.",
        "cause": "Fungus (Cercospora zeae-maydis), thrives in humid, warm conditions.",
        "treatment": "Apply foliar fungicide if the infection is severe and early in the season.",
        "prevention": "Rotate crops, use resistant hybrids, and manage crop residue.",
    },
    "Corn_(maize)___Common_rust_": {
        "name": "Corn Common Rust",
        "symptoms": "Small, reddish-brown, powdery pustules scattered on both leaf surfaces.",
        "cause": "Fungus (Puccinia sorghi).",
        "treatment": "Fungicide application if infection is heavy on susceptible hybrids.",
        "prevention": "Plant resistant hybrids; avoid late planting in high-risk areas.",
    },
    "Corn_(maize)___Northern_Leaf_Blight": {
        "name": "Corn Northern Leaf Blight",
        "symptoms": "Long, cigar-shaped grayish-green to tan lesions on leaves.",
        "cause": "Fungus (Exserohilum turcicum).",
        "treatment": "Fungicide application; residue management after harvest.",
        "prevention": "Use resistant hybrids and rotate with non-host crops.",
    },
    "Corn_(maize)___healthy": {
        "name": "Healthy Corn Leaf",
        "symptoms": "No disease symptoms detected.",
        "cause": "N/A",
        "treatment": "No treatment needed.",
        "prevention": "Balanced fertilization and routine field scouting.",
    },
    "Grape___Black_rot": {
        "name": "Grape Black Rot",
        "symptoms": "Circular tan leaf spots with dark borders; berries shrivel into hard black 'mummies'.",
        "cause": "Fungus (Guignardia bidwellii).",
        "treatment": "Remove mummified berries and infected canes; apply fungicide before bloom.",
        "prevention": "Prune for airflow; sanitize the vineyard floor each dormant season.",
    },
    "Grape___Esca_(Black_Measles)": {
        "name": "Grape Esca (Black Measles)",
        "symptoms": "Tiger-stripe interveinal discoloration on leaves; dark spots on berries.",
        "cause": "A complex of wood-rotting fungi entering through pruning wounds.",
        "treatment": "No full cure; remove and destroy severely infected vines/wood.",
        "prevention": "Prune during dry weather; protect large pruning cuts.",
    },
    "Grape___Leaf_blight_(Isariopsis_Leaf_Spot)": {
        "name": "Grape Leaf Blight (Isariopsis Leaf Spot)",
        "symptoms": "Dark brown angular spots on leaves that may merge and cause defoliation.",
        "cause": "Fungus (Pseudocercospora vitis / Isariopsis).",
        "treatment": "Apply fungicide; remove heavily infected leaves.",
        "prevention": "Ensure good canopy airflow and avoid overhead irrigation.",
    },
    "Grape___healthy": {
        "name": "Healthy Grape Leaf",
        "symptoms": "No disease symptoms detected.",
        "cause": "N/A",
        "treatment": "No treatment needed.",
        "prevention": "Routine vineyard monitoring and canopy management.",
    },
    "Orange___Haunglongbing_(Citrus_greening)": {
        "name": "Citrus Greening (Huanglongbing)",
        "symptoms": "Blotchy mottled leaves, lopsided bitter fruit, and yellow shoots.",
        "cause": "Bacterium spread by the Asian citrus psyllid insect.",
        "treatment": "No cure; remove and destroy infected trees to limit spread; control psyllid vector.",
        "prevention": "Use certified disease-free nursery stock; control psyllid populations.",
    },
    "Peach___Bacterial_spot": {
        "name": "Peach Bacterial Spot",
        "symptoms": "Small water-soaked, dark angular spots on leaves; pitted lesions on fruit.",
        "cause": "Bacterium (Xanthomonas arboricola pv. pruni).",
        "treatment": "Copper-based bactericide sprays during dormant and early season.",
        "prevention": "Plant resistant varieties; avoid overhead irrigation.",
    },
    "Peach___healthy": {
        "name": "Healthy Peach Leaf",
        "symptoms": "No disease symptoms detected.",
        "cause": "N/A",
        "treatment": "No treatment needed.",
        "prevention": "Routine orchard monitoring and balanced care.",
    },
    "Pepper,_bell___Bacterial_spot": {
        "name": "Bell Pepper Bacterial Spot",
        "symptoms": "Small water-soaked spots on leaves turning brown; scabby raised spots on fruit.",
        "cause": "Bacterium (Xanthomonas species).",
        "treatment": "Copper-based sprays; remove severely infected plants.",
        "prevention": "Use disease-free seed/transplants; avoid working in wet fields.",
    },
    "Pepper,_bell___healthy": {
        "name": "Healthy Bell Pepper Leaf",
        "symptoms": "No disease symptoms detected.",
        "cause": "N/A",
        "treatment": "No treatment needed.",
        "prevention": "Balanced watering and fertilization.",
    },
    "Potato___Early_blight": {
        "name": "Potato Early Blight",
        "symptoms": "Dark brown spots with concentric rings ('target spot') on older leaves first.",
        "cause": "Fungus (Alternaria solani).",
        "treatment": "Apply fungicide; remove infected foliage.",
        "prevention": "Rotate crops; avoid overhead watering; ensure plant vigor with balanced fertility.",
    },
    "Potato___Late_blight": {
        "name": "Potato Late Blight",
        "symptoms": "Water-soaked, rapidly enlarging dark lesions on leaves; white fuzzy growth under humid conditions.",
        "cause": "Oomycete (Phytophthora infestans) — the cause of the historic Irish potato famine.",
        "treatment": "Apply fungicide immediately; remove and destroy infected plants to stop spread fast.",
        "prevention": "Use certified seed potatoes; avoid overhead irrigation; monitor closely in cool, wet weather.",
    },
    "Potato___healthy": {
        "name": "Healthy Potato Leaf",
        "symptoms": "No disease symptoms detected.",
        "cause": "N/A",
        "treatment": "No treatment needed.",
        "prevention": "Routine field scouting and balanced fertilization.",
    },
    "Raspberry___healthy": {
        "name": "Healthy Raspberry Leaf",
        "symptoms": "No disease symptoms detected.",
        "cause": "N/A",
        "treatment": "No treatment needed.",
        "prevention": "Prune canes for airflow and monitor regularly.",
    },
    "Soybean___healthy": {
        "name": "Healthy Soybean Leaf",
        "symptoms": "No disease symptoms detected.",
        "cause": "N/A",
        "treatment": "No treatment needed.",
        "prevention": "Crop rotation and routine field scouting.",
    },
    "Squash___Powdery_mildew": {
        "name": "Squash Powdery Mildew",
        "symptoms": "White powdery patches on leaf surfaces, eventually covering whole leaves.",
        "cause": "Fungus, favored by warm dry days with humid nights.",
        "treatment": "Apply sulfur or potassium bicarbonate-based fungicide; remove heavily infected leaves.",
        "prevention": "Space plants for airflow; choose resistant varieties.",
    },
    "Strawberry___Leaf_scorch": {
        "name": "Strawberry Leaf Scorch",
        "symptoms": "Small purple spots that merge into larger scorched-looking blotches.",
        "cause": "Fungus (Diplocarpon earlianum).",
        "treatment": "Apply fungicide; remove old infected leaves after harvest.",
        "prevention": "Avoid overhead watering; ensure good bed airflow.",
    },
    "Strawberry___healthy": {
        "name": "Healthy Strawberry Leaf",
        "symptoms": "No disease symptoms detected.",
        "cause": "N/A",
        "treatment": "No treatment needed.",
        "prevention": "Routine monitoring and balanced watering.",
    },
    "Tomato___Bacterial_spot": {
        "name": "Tomato Bacterial Spot",
        "symptoms": "Small dark water-soaked spots on leaves and fruit, often with a yellow halo.",
        "cause": "Bacterium (Xanthomonas species).",
        "treatment": "Copper-based bactericide sprays; remove infected debris.",
        "prevention": "Use disease-free seed; avoid overhead watering.",
    },
    "Tomato___Early_blight": {
        "name": "Tomato Early Blight",
        "symptoms": "Brown target-like spots with concentric rings on lower/older leaves.",
        "cause": "Fungus (Alternaria solani).",
        "treatment": "Apply fungicide; remove and destroy affected leaves.",
        "prevention": "Rotate crops; mulch to reduce soil splash; stake plants for airflow.",
    },
    "Tomato___Late_blight": {
        "name": "Tomato Late Blight",
        "symptoms": "Large water-soaked greasy-looking lesions that spread quickly; white mold on undersides in humid conditions.",
        "cause": "Oomycete (Phytophthora infestans).",
        "treatment": "Apply fungicide immediately; remove and destroy infected plants fast to limit spread.",
        "prevention": "Avoid overhead irrigation; ensure good spacing and airflow.",
    },
    "Tomato___Leaf_Mold": {
        "name": "Tomato Leaf Mold",
        "symptoms": "Pale yellow spots on upper leaf surface, olive-green mold underneath.",
        "cause": "Fungus (Passalora fulva), favored by high humidity.",
        "treatment": "Improve ventilation; apply fungicide if severe.",
        "prevention": "Reduce humidity in greenhouses; avoid wetting foliage.",
    },
    "Tomato___Septoria_leaf_spot": {
        "name": "Tomato Septoria Leaf Spot",
        "symptoms": "Small circular spots with dark borders and gray centers, mainly on lower leaves.",
        "cause": "Fungus (Septoria lycopersici).",
        "treatment": "Remove infected leaves; apply fungicide.",
        "prevention": "Mulch soil, avoid overhead watering, rotate crops.",
    },
    "Tomato___Spider_mites Two-spotted_spider_mite": {
        "name": "Tomato Spider Mite Damage",
        "symptoms": "Fine yellow speckling/stippling on leaves, fine webbing in severe cases.",
        "cause": "Two-spotted spider mite infestation, favored by hot dry conditions.",
        "treatment": "Apply miticide or insecticidal soap; increase humidity around plants.",
        "prevention": "Regular monitoring, avoid drought stress, encourage natural predators.",
    },
    "Tomato___Target_Spot": {
        "name": "Tomato Target Spot",
        "symptoms": "Brown lesions with concentric rings, similar to early blight, on leaves and fruit.",
        "cause": "Fungus (Corynespora cassiicola).",
        "treatment": "Apply fungicide; remove infected foliage.",
        "prevention": "Improve airflow and avoid leaf wetness.",
    },
    "Tomato___Tomato_Yellow_Leaf_Curl_Virus": {
        "name": "Tomato Yellow Leaf Curl Virus",
        "symptoms": "Upward curling, yellowing leaves and stunted plant growth.",
        "cause": "Virus spread by whiteflies.",
        "treatment": "No cure; remove infected plants; control whitefly populations.",
        "prevention": "Use resistant varieties and whitefly-proof netting/screens.",
    },
    "Tomato___Tomato_mosaic_virus": {
        "name": "Tomato Mosaic Virus",
        "symptoms": "Mottled light/dark green mosaic pattern on leaves, stunted growth.",
        "cause": "Virus, easily spread by contact/handling and contaminated tools.",
        "treatment": "No cure; remove and destroy infected plants; disinfect tools.",
        "prevention": "Use resistant varieties; wash hands and sanitize tools between plants.",
    },
    "Tomato___healthy": {
        "name": "Healthy Tomato Leaf",
        "symptoms": "No disease symptoms detected.",
        "cause": "N/A",
        "treatment": "No treatment needed.",
        "prevention": "Balanced watering, staking, and routine monitoring.",
    },
}


def get_info(class_name: str) -> dict:
    """Return info dict for a class name, with a safe fallback."""
    return DISEASE_INFO.get(
        class_name,
        {
            "name": class_name,
            "symptoms": "No details available.",
            "cause": "N/A",
            "treatment": "Please consult a local agricultural expert.",
            "prevention": "N/A",
        },
    )
